### ISSUE TITLE
ZEUS# java.io.IOException: Cannot run program "hive" (in directory 

### ISSUE THREAD

**Issue by phenixmzy** [alibaba/zeus#47]
ZEUS# 2015-03-15 22:47:56 进入任务队列
ZEUS# 2015-03-15 22:47:58 开始运行
ZEUS# 开始执行前置处理单元：DownloadJob
ZEUS# 前置处理单元：DownloadJob 处理完毕
ZEUS# 开始执行核心Job任务
ZEUS# DEBUG Command:hive -f /data2/zeus/run_job_dir/2015-03-15/debug-13/1426430878285.hive
ZEUS# java.io.IOException: Cannot run program "hive" (in directory "/data2/zeus/run_job_dir/2015-03-15/debug-13"): java.io.IOException: error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:470)
at com.taobao.zeus.jobs.ProcessJob.run(ProcessJob.java:194)
at com.taobao.zeus.jobs.sub.HiveJob.runInner(HiveJob.java:82)
at com.taobao.zeus.jobs.sub.HiveJob.run(HiveJob.java:49)
at com.taobao.zeus.jobs.WithProcesserJob.run(WithProcesserJob.java:66)
at com.taobao.zeus.socket.worker.reqresp.WorkerBeExecute$2.call(WorkerBeExecute.java:164)
at com.taobao.zeus.socket.worker.reqresp.WorkerBeExecute$2.call(WorkerBeExecute.java:140)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:662)
Caused by: java.io.IOException: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.(UNIXProcess.java:148)
at java.lang.ProcessImpl.start(ProcessImpl.java:65)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
... 11 more

**Comment by phenixmzy** [comment]
请问 这个 什么 问题啊？我直接 在 shell 里执行 hive -f /data2/zeus/run_job_dir/2015-03-15/debug-13/1426430878285.hive 是 可以的

**Comment by cxzl25** [comment]
环境变量的问题
