### ISSUE TITLE
调度shell脚本报core-site.xml not found

### ISSUE THREAD

**Issue by bylijinnan** [alibaba/zeus#52]
shell 执行hdfs -dfs -put xxx yyyy命令，在shell脚本所在的机器上直接执行成功，但通过zeus平台调用则报错：
Exception in thread "main" java.lang.RuntimeException: core-site.xml not found
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2257)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2185)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2102)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:979)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:953)
	at org.apache.hadoop.conf.Configuration.setBoolean(Configuration.java:1289)
	at org.apache.hadoop.util.GenericOptionsParser.processGeneralOptions(GenericOptionsParser.java:320)
	at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:478)
	at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:171)
	at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:154)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:64)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:308)

是什么原因呢？谢谢

**Comment by abop** [comment]
环境变量问题

bylijinnan
notifications@github.com>于2015年10月30日 周五16:27写道：
