### ISSUE TITLE
hive conf读的位置不对

### ISSUE THREAD

**Issue by fengjian428** [alibaba/zeus#59]
![wangwang20161125121156](https://cloud.githubusercontent.com/assets/4403474/20614351/682fa9ac-b308-11e6-97e6-452f89180cb3.png)
在zeus2中读的位置不对，zeus中可以正确读取，HIVE_HOME已经配置了

**Comment by fengjian428** [comment]
然后跑zeus的时候会报 Class org.datanucleus.api.jdo.JDOPersistenceManagerFactory was not found.
有人遇到过吗

**Comment by ddhuyang** [comment]
我也遇到了这个问题，不知道在哪配置读取hive元数据库的相关信息。请问最后解决了这个问题了吗？

**Comment by GallantKong** [comment]
我也遇到了相同的问题,请问最后解决了这个问题了吗？
        at com.taobao.zeus.store.CliTableManager.<init>(CliTableManager.java:38)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:100)
        ... 46 more
Caused by: java.lang.ClassNotFoundException: org.datanucleus.api.jdo.JDOPersistenceManagerFactory
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1280)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1114)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at javax.jdo.JDOHelper$18.run(JDOHelper.java:2009)
        at javax.jdo.JDOHelper$18.run(JDOHelper.java:2007)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.jdo.JDOHelper.forName(JDOHelper.java:2006)
        at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1155)
