### ISSUE TITLE
schedule.log 报错 说是/tmp/zeus/2017-01-09  no such file or directory

### ISSUE THREAD

**Issue by FunkyYang** [alibaba/zeus#61]
您好：
schedule.log 报错 说是/tmp/zeus/2017-01-09  no such file or directory ,但是我去查看了之后是有的
```
java.io.IOException: Cannot run program "dos2unix" (in directory "/tmp/zeus/2017-01-09"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at com.taobao.zeus.jobs.ProcessJob.run(ProcessJob.java:194)
        at com.taobao.zeus.jobs.sub.ShellJob.run(ShellJob.java:37)
        at com.taobao.zeus.jobs.sub.tool.MemUseRateJob.run(MemUseRateJob.java:34)
        at com.taobao.zeus.socket.worker.reqresp.WorkerHeartBeat.execute(WorkerHeartBeat.java:39)
        at com.taobao.zeus.socket.worker.ClientWorker$2.run(ClientWorker.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
```
请问是我哪里设置的不对么
```
root@datanode03:/tmp/zeus/2017-01-09# pwd
/tmp/zeus/2017-01-09
```

**Comment by abop** [comment]
应该是 dos2unix 这个没在path里。你看下你的 linux 发行版是不是没有这个程序。没有的话自己装一个。

**Comment by FunkyYang** [comment]
谢谢，确实没有。
